# Generated by Django 4.2.1 on 2023-05-15 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Librarians',
            new_name='Librarian',
        ),
    ]
