# Generated by Django 4.2.1 on 2023-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0002_rename_librarians_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='email',
            field=models.EmailField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='institute_id',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
